UIKit
Dante13Dark/lessons-JS-core pull request #5
Opened 2022-08-21 21:48 UTC by Dante13Dark

GitHubPages: https://dante13dark.github.io/lessons-JS-core/UIKit/UIKit.html

2022-08-22 18:16 UTC, Dante13Dark commented
прогнал код через prettier

2022-08-23 23:10 UTC, Muslik requested changes
- цвет placeholder в searchbar не как на макете
- radio, checkbox в dropdown должны быть по высоте и длине как ```li```

2022-08-23 23:10 UTC, Muslik commented on UIKit/UIKit.html
> +            <div class="button__icon-container">
Зачем нужна лишняя обертка

2022-08-24 17:20 UTC, Dante13Dark commented on UIKit/UIKit.html
> +            <div class="button__icon-container">
поправил цвета у searchbar, убрал лишние контейнеры у иконок, чекбокса, радио и у них же в дропдаунах, растянул их на всю ячейку списка

2022-08-27 22:11 UTC, Muslik approved these changes

2022-08-28 12:57 UTC, merged